import { useEffect, useState } from 'react';
import { api } from '../api/client';
import { useAuth } from '../context/AuthContext';

interface Report { id: number; title: string; framework_name: string; score: number; generated_by_name: string; created_at: string; summary: Record<string, number>; }

export function ReportsPage() {
  const { user } = useAuth();
  const [reports, setReports] = useState<Report[]>([]);
  const [generating, setGenerating] = useState('');
  const canGenerate = user?.role === 'admin' || user?.role === 'auditor';

  function loadReports() {
    api.get('/api/reports').then(r => setReports(r.data.reports)).catch(() => {});
  }
  useEffect(() => { loadReports(); }, []);

  async function generateReport(slug: string) {
    setGenerating(slug);
    try {
      const res = await api.post('/api/reports/generate', { frameworkSlug: slug }, { responseType: 'blob' });
      const url = URL.createObjectURL(new Blob([res.data], { type: 'application/pdf' }));
      const a = document.createElement('a');
      a.href = url;
      a.download = `${slug}-compliance-report.pdf`;
      a.click();
      URL.revokeObjectURL(url);
      loadReports();
    } catch { /* ignore */ }
    finally { setGenerating(''); }
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
      <div>
        <h1 style={{ fontSize: 24, fontWeight: 700, color: '#f1f5f9' }}>Reports</h1>
        <p style={{ color: '#64748b', marginTop: 4 }}>Generate and download PDF compliance reports</p>
      </div>

      {/* Generate buttons */}
      {canGenerate && (
        <div style={{ background: '#1e293b', borderRadius: 12, padding: 24 }}>
          <h2 style={{ fontSize: 15, fontWeight: 600, color: '#94a3b8', marginBottom: 16 }}>Generate New Report</h2>
          <div style={{ display: 'flex', gap: 12 }}>
            {[
              { slug: 'gdpr',     name: 'GDPR',      color: '#3b82f6' },
              { slug: 'iso27001', name: 'ISO 27001',  color: '#8b5cf6' },
              { slug: 'hipaa',    name: 'HIPAA',      color: '#06b6d4' },
            ].map(f => (
              <button key={f.slug} onClick={() => generateReport(f.slug)} disabled={!!generating}
                style={{ background: generating === f.slug ? '#334155' : f.color, color: '#fff', border: 'none',
                  borderRadius: 8, padding: '12px 24px', fontSize: 14, fontWeight: 600, cursor: generating ? 'wait' : 'pointer' }}>
                {generating === f.slug ? `Generating ${f.name}…` : `📄 ${f.name} Report`}
              </button>
            ))}
          </div>
          <p style={{ fontSize: 12, color: '#475569', marginTop: 12 }}>PDF includes controls list, risk register, and compliance score. Downloads automatically.</p>
        </div>
      )}

      {/* Report history */}
      <div style={{ background: '#1e293b', borderRadius: 12, padding: 24 }}>
        <h2 style={{ fontSize: 15, fontWeight: 600, color: '#94a3b8', marginBottom: 16 }}>Report History</h2>
        {reports.length === 0 && <p style={{ color: '#475569', fontSize: 14 }}>No reports generated yet.</p>}
        {reports.length > 0 && (
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
            <thead>
              <tr style={{ borderBottom: '1px solid #334155' }}>
                {['Title', 'Framework', 'Score', 'Generated By', 'Date', 'Summary'].map(h => (
                  <th key={h} style={{ padding: '10px 14px', color: '#64748b', textAlign: 'left', fontWeight: 500 }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {reports.map(r => {
                const color = r.score >= 75 ? '#34d399' : r.score >= 50 ? '#fbbf24' : '#f87171';
                return (
                  <tr key={r.id} style={{ borderBottom: '1px solid #0f172a' }}>
                    <td style={{ padding: '10px 14px', color: '#e2e8f0' }}>{r.title}</td>
                    <td style={{ padding: '10px 14px', color: '#94a3b8' }}>{r.framework_name}</td>
                    <td style={{ padding: '10px 14px' }}>
                      <span style={{ color, fontWeight: 700, fontSize: 16 }}>{r.score}%</span>
                    </td>
                    <td style={{ padding: '10px 14px', color: '#64748b' }}>{r.generated_by_name}</td>
                    <td style={{ padding: '10px 14px', color: '#475569', fontSize: 12 }}>
                      {new Date(r.created_at).toLocaleString('en-GB')}
                    </td>
                    <td style={{ padding: '10px 14px', color: '#64748b', fontSize: 11, fontFamily: 'monospace' }}>
                      {r.summary ? `✓${r.summary.compliant} ~${r.summary.partial} ✗${r.summary.non_compliant}` : ''}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
